project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Hongming Guo"
  favicon: images/logo.png

  page-footer:
    left: |
      Hongming Guo
    right: |
      Built with [Quarto](https://quarto.org/)

  navbar:
    background: "#DCCFF3"
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "CV"
        href: CV.md
      - text: "Notes"
        href: notes.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Chinese"
        href: Chinese.qmd

format:
  html:
    theme: styles.scss
    toc: true
    toc-position: right
    toc-depth: 3
